Repository PaulRBerg/create-eth-app, pull requests merged in 2020-11, with the labels that each got.

#94 refactor: dryify template tests
  test/integration/templates.test.ts
  test/unit/directories.test.ts
Labels: enhancement

#96 Add mStable template
  .eslintignore
  src/helpers/constants.ts
  templates/react/mstable/README.md.ctx
  templates/react/mstable/package.json.ctx
  templates/react/mstable/packages/contracts/README.md.ctx
  templates/react/mstable/packages/contracts/package.json.ctx
  templates/react/mstable/packages/contracts/src/abis.js
  templates/react/mstable/packages/contracts/src/abis/mAsset.json
  templates/react/mstable/packages/contracts/src/abis/metaToken.json
  templates/react/mstable/packages/contracts/src/abis/nexus.json
  templates/react/mstable/packages/contracts/src/abis/savingsContract.json
  templates/react/mstable/packages/contracts/src/abis/savingsManager.json
  templates/react/mstable/packages/contracts/src/addresses.js
  templates/react/mstable/packages/contracts/src/index.js.ctx
  templates/react/mstable/packages/react-app/README.md.ctx
  templates/react/mstable/packages/react-app/package.json.ctx
  templates/react/mstable/packages/react-app/src/App.js.ctx
  templates/react/mstable/packages/react-app/src/graphql/subgraph.js
  templates/react/mstable/packages/react-app/src/index.js.ctx
  templates/vue/mstable/README.md.ctx
  templates/vue/mstable/package.json.ctx
  templates/vue/mstable/packages/contracts/README.md.ctx
  templates/vue/mstable/packages/contracts/package.json.ctx
  templates/vue/mstable/packages/contracts/src/abis.js
  templates/vue/mstable/packages/contracts/src/abis/mAsset.json
  templates/vue/mstable/packages/contracts/src/abis/metaToken.json
  templates/vue/mstable/packages/contracts/src/abis/nexus.json
  templates/vue/mstable/packages/contracts/src/abis/savingsContract.json
  templates/vue/mstable/packages/contracts/src/abis/savingsManager.json
  templates/vue/mstable/packages/contracts/src/addresses.js
  templates/vue/mstable/packages/contracts/src/index.js.ctx
  templates/vue/mstable/packages/vue-app/README.md.ctx
  templates/vue/mstable/packages/vue-app/package.json.ctx
  templates/vue/mstable/packages/vue-app/src/components/HelloWorld.vue.ctx
  templates/vue/mstable/packages/vue-app/src/graphql/subgraph.js
  templates/vue/mstable/packages/vue-app/src/main.js.ctx
Labels: feature

#102 Delete null assignments in balancer react template
  CHANGELOG.md
  package.json
  templates/react/balancer/packages/react-app/src/App.js.ctx
Labels: bug
